name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: 1.86.0
          targets: x86_64-unknown-illumos

      - name: generate documentation
        run: |
          cargo doc --no-deps --target x86_64-unknown-illumos
        
      - name: prep deployment branch
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p dist
          cp -r target/x86_64-unknown-illumos/doc/* dist/
          cd dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
          
      - name: push deployment branch
        if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@4cc74773234f74829a8c21bc4d69dd4be9cfa599 # v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./dist
